#!/bin/sh
#Daemon for Modemmanager.Restart modem.
#autor https://github.com/yosh781

trap "logger 'Modem watchdog stopped'; exit 0" INT TERM

if ! uci -q get network.wan >/dev/null; then
    logger "Interface wan not found in network config, exiting"
    exit 0
fi

LTEPROTO=$(uci -q get network.wan.proto)
if [ "$LTEPROTO" != "modemmanager" ]; then
    logger "WAN interface is not using modemmanager, exiting"
    exit 0
fi

AUTOCONNECT=$(uci -q get network.wan.autoconnect)
if [ "$AUTOCONNECT" != "1" ]; then
    logger "WAN autoconnect is disabled, exiting"
    exit 0
fi

while true; do
MODEM_PATH=$(mmcli -L --timeout 5000 | awk '/Modem/ {print $1}' | head -1)

if [ -z "$MODEM_PATH" ]; then
    logger "mmcli doesn't see modem, trying to find modem..." 
    if [ -e "/dev/ttyUSB2" ]; then
        echo -e "AT+CFUN=1,1\r" > /dev/ttyUSB2
        sleep 15
    else
        logger "no port /dev/ttyUSB2!"
    fi
    
    logger "reboot router..."
    reboot
    
fi
   sleep 10 
done

exit 0
