#!/bin/sh
#Daemon for Modemmanager.Restart modem.
#autor https://github.com/yosh781

trap "logger 'Modem watchdog stopped'; exit 0" INT TERM


if ! uci -q get network.wan >/dev/null; then
    logger "Interface wan not found in network config, exiting"
    exit 0
fi


LTEPROTO=$(uci -q get network.wan.proto)
if [ "$LTEPROTO" != "modemmanager" ]; then
    logger "WAN interface is not using modemmanager, exiting"
    exit 0
fi


AUTOCONNECT=$(uci -q get network.wan.autoconnect)
if [ "$AUTOCONNECT" != "1" ]; then
    logger "WAN autoconnect is disabled, exiting"
    exit 0
fi

while true; do
MODEM_PATH=$(mmcli -L | awk '/Modem/ {print $1}' | head -1)

if [ -z "$MODEM_PATH" ]; then
    logger "mmcli doesn't see modem, trying to reset..."
    /etc/init.d/network restart
    continue
fi

STATUS=$(mmcli -m "${MODEM_PATH}" --output-keyvalue)
APN=$(echo "$STATUS" | grep "modem.3gpp.eps.initial-bearer.settings.apn" | cut -d ':' -f2)
APN=${APN:-"internet"}
LTESTATUS=$(mmcli -m "${MODEM_PATH}" | grep -c "connected")
   
 if [ "$LTESTATUS" -eq 0 ]; then
    logger "Modem is not connected, trying to connect..."
    mmcli -m "${MODEM_PATH}" --simple-connect="apn=$APN"
	sleep 5
            
    logger "network restart..."
    uci set network.wan.disabled=0  
    uci commit network                
    /etc/init.d/network reload    
 
 fi

    sleep 10 
done

exit 0
